logging:
    file:
        name: /logs/sboard.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
server:
    port: 8080
    servlet:
        context-path: /sboard

spring:
    application:
        name: sboard
        version: ${version}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.202.37.221:3306/jboard
        username: root
        password: "~~##ASzx5623"
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: soc23231@gmail.com
        password: fzzvlajeekgbfces # google 앱 비밀번호
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    thymeleaf:
        prefix: classpath:/templates

    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB



